import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cookies } from 'next/headers';
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Header from '@/components/header'; // added
import { SESSION_COOKIE_NAME } from '@/constants'; // added

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	  // added
	  const cookieStore = await cookies()
	  const session = cookieStore.get(SESSION_COOKIE_NAME)?.value || null;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
		<Header session={session} />
        {children}
      </body>
    </html>
  );
}
